config/routes.rb
Hearthstoniav2::Application.routes.draw do


  mount RedactorRails::Engine => '/redactor_rails'
  resources :tags

  root 'questions#index'

  devise_for :users

  get 'users/:id' => 'users#show', as: :user

  resources :questions do
    resources :answers do
      member do
        get :upvote
        get :downvote
      end
    end
    member do
      get :upvote
      get :downvote
    end
  end

  get "users/show"
  get 'about' => 'pages#about'
end

app/models/question.rb
class Question < ActiveRecord::Base
  is_impressionable
  acts_as_votable

  extend FriendlyId
  friendly_id :title, :use => [:slugged, :finders, :history]

  belongs_to :user
  
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :answers, :dependent => :destroy

  validates :title, :presence => true
  validates :body, :presence => true

  # Tags
  def self.tagged_with(name)
    Tag.find_by_name!(name).questions
  end

  def tag_list
    tags.map(&:name)
  end

  def tag_with(tags)
    old_tags = self.tags.pluck(:name).unshift("")
    unless old_tags == tags # if tags were not updated no action will be done.
      self.tags.delete_all
      # code here (in the future)
      tags.map do |n|
        tag = Tag.where(name: n.strip).first
        if tag.present?
          tagging = Tagging.find_or_create_by_tag_id_and_question_id(tag.id, self.id)
          #Tagging.create(tag_id: tag.id, question_id: self.id)
        end
      end
    end
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first!
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # Impressionist
  impressionist :actions => [:show]

  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # CanCan
  load_and_authorize_resource except: [:create]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order("created_at DESC")
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
    impressionist(@question)
  end

  # GET /questions/new
  def new
    @question = current_user.questions.build
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        @question.tag_with(params[:question][:tag_list])
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        @question.tag_with(params[:question][:tag_list])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  # Upvote Question
  def upvote
    @question = Question.find(params[:id])
    @question.upvote_from current_user
    increment_votes_count
    @question.user.add_points(5)
    redirect_to @question
  end

  # Downvote Question
  def downvote
    @question = Question.find(params[:id])
    @question.downvote_from current_user
    decrement_votes_count
    @question.user.substract_points(2)
    redirect_to @question
  end

  def decrement_votes_count
    @question.decrement!(:votes_count)
    @question.save
  end

  def increment_votes_count
    @question.increment!(:votes_count)
    @question.save
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body, :slug, :answer, :tag_list)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="row">
  <div class="col-md-9">
    <%= form_for(@question, html: { multipart: true }) do |f| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">
          <h1>Ask a Question</h1>
        </div>
      </div>

      <div class="panel-body">
          <% if @question.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

              <ul>
                <% @question.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :title %><br>
            <%= f.text_field :title, class: "form-control", :autofocus => true,
                placeholder: "What's your Hearthstone Question. Be specific"%>
          </div>

          <div class="form-group">
            <%= f.label :body %><br>
            <%= f.text_area :body, class: "redactor redactor-box" %>
          </div>

          <div class="form-group">
            <%= f.collection_select :tag_list, Tag.order(:name), :name, :name, {}, {multiple: true} %>
          </div>
          
        </div>


        <div class="panel-footer">
          <button type="submit" class="ui-button button1">
            <span class="button-left">
              <span class="button-right"> Post your Question</span>
            </span>
          </button>
        </div>

      </div>
    <% end %>
  </div>

  <div class="col-md-3">
    <button data-toggle="modal" data-target="#KeyboardShortcuts" class="ui-button button1">
            <span class="button-left">
              <span class="button-right"><span class="glyphicon glyphicon-ok-circle"></span> Keyboard Shortcuts</span>
            </span>
    </button>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="KeyboardShortcuts" tabindex="-1" role="dialog" aria-labelledby="KeyboardShortcuts" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><b>Keyboard shortcuts</b></h4>
      </div>
      <div class="modal-body">
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <td></td>
            <td>OS X</td>
            <td>Windows</td>
          </tr>
          </thead>
          <tbody><tr>
            <td>Undo</td>
            <td><kbd>Cmd + z</kbd></td>
            <td><kbd>Ctrl + z</kbd></td>
          </tr>
          <tr>
            <td>Redo</td>
            <td><kbd>Cmd + Shift + z</kbd></td>
            <td><kbd>Ctrl + Shift + z</kbd></td>
          </tr>
          <tr>
            <td>Increase indent</td>
            <td><kbd>Tab</kbd></td>
            <td><kbd>Tab</kbd></td>
          </tr>
          <tr>
            <td>Decrease indent</td>
            <td><kbd>Shift + Tab</kbd></td>
            <td><kbd>Shift + Tab</kbd></td>
          </tr>
          <tr>
            <td>Clear formatting</td>
            <td><kbd>Cmd + m</kbd></td>
            <td><kbd>Ctrl + m</kbd></td>
          </tr>
          <tr>
            <td>Bold</td>
            <td><kbd>Cmd + b</kbd></td>
            <td><kbd>Ctrl + b</kbd></td>
          </tr>
          <tr>
            <td>Italic</td>
            <td><kbd>Cmd + i</kbd></td>
            <td><kbd>Ctrl + i</kbd></td>
          </tr>
          <tr>
            <td>Numbered list</td>
            <td><kbd>Cmd + k</kbd></td>
            <td><kbd>Ctrl + k</kbd></td>
          </tr>
          <tr>
            <td>Bulleted list</td>
            <td><kbd>Cmd + j</kbd></td>
            <td><kbd>Ctrl + j</kbd></td>
          </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/questions/_question.html.erb
<div class="question_module">

  <div class="qm_votes">
    <div class="qm_count"><%= question.votes_count %></div>
    <div><%= "vote".pluralize(question.votes_count) %></div>
  </div>

  <div class="qm_status">
    <div class="qm_count"><%= question.answers.count %></div>
    <div><%= "answer".pluralize(question.answers.count) %></div>
  </div>

  <div class="qm_views">
    <div class="qm_count"><%= question.impressionist_count(:filter=>:session_hash) %></div>
    <div><%= "view".pluralize(question.impressionist_count(:filter=>:session_hash)) %></div>
  </div>

  <div class="qm_summary">

    <h3><%= link_to question.title, question %></h3>
    <ul class="ui-pagination">
      <% question.tags.each do |tag| %>
        <li>
          <%= link_to tag do %>
            <span><%= tag.name %></span>
          <% end %>
        </li>
      <% end %>
    </ul>

    <div class="qm_info">
      <%= time_ago_in_words(question.created_at) %> ago
      <span class="qm_info_user">
        <%= link_to question.user.user_name, question.user %>
      </span>
      <%= question.user.points %>
    </div>

  </div>

</div>

app/views/questions/edit.html.erb
<div class="row">
  <div class="col-md-9">
    <%= form_for(@question, html: { multipart: true }) do |f| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title">
            <h1>Edit your Question</h1>
          </div>
        </div>

        <div class="panel-body">
          <% if @question.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

              <ul>
                <% @question.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :title %><br>
            <%= f.text_field :title, class: "form-control", :autofocus => true,
                             placeholder: "What's your Hearthstone Question. Be specific"%>
          </div>

          <div class="form-group">
            <%= f.label :body %><br>
            <%= f.text_area :body, class: "redactor redactor-box" %>
          </div>

          <div class="form-group">
            <%= f.collection_select :tag_list, Tag.order(:name), :name, :name, {}, {multiple: true} %>
          </div>

        </div>


        <div class="panel-footer">

          <button type="submit" class="ui-button button1">
            <span class="button-left">
              <span class="button-right"> Edit your Question</span>
            </span>
          </button>

          <a href="javascript:history.back()">
            <button class="ui-button button1">
            <span class="button-left">
              <span class="button-right"> Back </span>
            </span>
            </button>
          </a>

        </div>

      </div>
    <% end %>
  </div>

  <div class="col-md-3">
    <button data-toggle="modal" data-target="#KeyboardShortcuts" class="ui-button button1">
            <span class="button-left">
              <span class="button-right"><span class="glyphicon glyphicon-ok-circle"></span> Keyboard Shortcuts</span>
            </span>
    </button>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="KeyboardShortcuts" tabindex="-1" role="dialog" aria-labelledby="KeyboardShortcuts" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><b>Keyboard shortcuts</b></h4>
      </div>
      <div class="modal-body">
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <td></td>
            <td>OS X</td>
            <td>Windows</td>
          </tr>
          </thead>
          <tbody><tr>
            <td>Undo</td>
            <td><kbd>Cmd + z</kbd></td>
            <td><kbd>Ctrl + z</kbd></td>
          </tr>
          <tr>
            <td>Redo</td>
            <td><kbd>Cmd + Shift + z</kbd></td>
            <td><kbd>Ctrl + Shift + z</kbd></td>
          </tr>
          <tr>
            <td>Increase indent</td>
            <td><kbd>Tab</kbd></td>
            <td><kbd>Tab</kbd></td>
          </tr>
          <tr>
            <td>Decrease indent</td>
            <td><kbd>Shift + Tab</kbd></td>
            <td><kbd>Shift + Tab</kbd></td>
          </tr>
          <tr>
            <td>Clear formatting</td>
            <td><kbd>Cmd + m</kbd></td>
            <td><kbd>Ctrl + m</kbd></td>
          </tr>
          <tr>
            <td>Bold</td>
            <td><kbd>Cmd + b</kbd></td>
            <td><kbd>Ctrl + b</kbd></td>
          </tr>
          <tr>
            <td>Italic</td>
            <td><kbd>Cmd + i</kbd></td>
            <td><kbd>Ctrl + i</kbd></td>
          </tr>
          <tr>
            <td>Numbered list</td>
            <td><kbd>Cmd + k</kbd></td>
            <td><kbd>Ctrl + k</kbd></td>
          </tr>
          <tr>
            <td>Bulleted list</td>
            <td><kbd>Cmd + j</kbd></td>
            <td><kbd>Ctrl + j</kbd></td>
          </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/questions/index.html.erb
<% unless user_signed_in? %>
<div class="heartstonia_welcome_jumbo">
  <h1>Welcome to Hearthstonia</h1>
  <br>
  <p>
    <%= link_to new_user_registration_path, class: "ui-button sub-beta-button" do %>
      <span class="button-content">Register for the Beta</span>
    <% end %>
  </p>
  <p class="hwj_link">
  <%= link_to "learn more", '#', class: "hwj_link" %>
  </p>
</div>
<% end %>


<div class="row">

  <div class="col-md-9">
    <%= render @questions %>
  </div>

  <div class="col-md-3">
    Here goes something
  </div>

</div>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<!--le Title-->
<div id="question-header">
  <h1>
    <%= link_to @question.title, @question, class: "question-hyperlink" %>
  </h1>
</div>

<!--le Body-->
<div class="row">
  <div class="col-md-9">

    <div class="question">
      <table>
        <tbody><tr>
          <td class="votecell">
            <div class="vote">

              <!--le Upvote-->
              <%= link_to upvote_question_path(@question), class: "question_vote_up" do %>
                <span class="glyphicon glyphicon-chevron-up"></span>
              <% end %>

              <!--le Votes Size-->
              <span class="question_vote_count">
                <%= @question.votes_count %>
              </span>

              <!--le Downvote-->
              <%= link_to downvote_question_path(@question), class: "question_vote_down" do %>
                <span class="glyphicon glyphicon-chevron-down"></span>
              <% end %>

              <!--le Favorites-->
              <div class="question_favorite">
                <span class="glyphicon glyphicon-heart-empty"></span>
              </div>

            </div>
          </td>

          <td class="postcell">
            <div>
              <div class="post-text">
                <%= sanitize(@question.body) %>
              </div>

              <table class="fw">
                <tbody>
                <tr>

                  <td class="vt">

                    <!--le Tags-->
                    <ul class="ui-pagination">
                      <% @question.tags.each do |tag| %>
                        <li>
                          <%= link_to tag do %>
                            <span><%= tag.name %></span>
                          <% end %>
                        </li>
                      <% end %>
                    </ul>


                    <div class="post-menu">

                      <%= link_to "#", class: "ui-button button2" do %>
                        <span class="button-left">
                          <span class="button-right">share</span>
                        </span>
                      <% end %>

                      <% if can? :update, @question %>
                        <%= link_to edit_question_path, class: "ui-button button2" do %>
                          <span class="button-left">
                            <span class="button-right">edit</span>
                          </span>
                        <% end %>
                      <% end %>

                      <% if can? :destroy, @question %>
                        <%= link_to @question,
                                    method: :delete, data: { confirm: 'Do you really want to delete this Question?' },
                                    class: "ui-button button2" do %>
                          <span class="button-left">
                            <span class="button-right">delete</span>
                          </span>
                        <% end %>
                      <% end %>

                      <%= link_to "#", class: "ui-button button2" do %>
                        <span class="button-left">
                          <span class="button-right">flag</span>
                        </span>
                      <% end %>


                    </div>
                  </td>

                  <td class="post-signature">

                    <div class="user-info ">
                      <div class="user-action-time">
                        asked <span title="#" class="relativetime"><%= time_ago_in_words(@question.created_at) %> ago</span>
                      </div>

                      <div class="user-avatar32">
                        <%= link_to @question.user do %>
                          <div>
                            <%= image_tag @question.user.avatar.url(:avatar) %>
                          </div>
                        <% end %>
                      </div>

                      <div class="user-details">
                        <%= link_to @question.user.user_name, @question.user %>
                        <br>
                        <span class="reputation-score" title="reputation score "><%= @question.user.points %></span>
                      </div>

                    </div>
                  </td>

                </tr>
                </tbody>
              </table>
            </div>
          </td>
        </tr>
        </tbody>
      </table>

    </div>

    <br>

    <!--le Answers-->
    <div class="answers_header">
      <% if @question.answers.present? %>
        <h2><%= pluralize(@question.answers.count, 'Answer')%></h2>
      <% else %>
        <h2>No answers yet (be the first one to answer)</h2>
      <% end %>
    </div>

    <%= render @question.answers.order("created_at DESC") %>

    <br>

    <!--le Form-->
    <%= form_for([@question, @question.answers.new]) do |f| %>

      <div class="form-group">
        <%= f.label "Your Answer" %><br>
        <%= f.text_area :body, class: "redactor redactor-box" %>
      </div>

      <div class="actions">
        <button type="submit" class="ui-button button1">
          <span class="button-left">
            <span class="button-right"> Post your Answer</span>
          </span>
        </button>
      </div>

    <% end %>


  </div>

  <div class="col-md-3">
    <table xmlns="http://www.w3.org/1999/xhtml" class="media-frame">
      <tr>
        <td class="tl"></td>
        <td class="tm">
          <span class="tm-left"></span>
          <span class="tm-mid"></span>
          <span class="tm-right"></span>
        </td>
        <td class="tr"></td>
      </tr>
      <tr>
        <td class="ml">
          <span class="ml-top"></span>
          <span class="ml-bottom"></span>
        </td>
        <td class="mm">
         <div class="yolo-swaggings">
          <table class="media-frame-unit-fix">
            <tbody>
            <tr>
              <td>
                <p class="label-key">asked</p>
              </td>
              <td style="padding-left: 10px">
                <p class="label-key"><b><%= time_ago_in_words @question.created_at %> ago</b></p>
              </td>
            </tr>
            <tr>
              <td>
                <p class="label-key">viewed</p>
              </td>

              <td style="padding-left: 10px">
                <p class="label-key">
                  <b><%= @question.impressionist_count(:filter=>:session_hash) %> times</b>
                </p>
              </td>
            </tr>
            </tbody>
          </table>
         </div>
        </td>
        <td class="mr">
          <span class="mr-top"></span>
          <span class="mr-bottom"></span>
        </td>
      </tr>
      <tr>
        <td class="bl"></td>
        <td class="bm">
          <span class="bm-left"></span>
          <span class="bm-mid"></span>
          <span class="bm-right"></span>
        </td>
        <td class="br"></td>
      </tr>
    </table>

  </div>
</div>