config/routes.rb
Hearthstoniav2::Application.routes.draw do


  mount RedactorRails::Engine => '/redactor_rails'
  resources :tags

  root 'questions#index'

  devise_for :users

  get 'users/:id' => 'users#show', as: :user

  resources :questions do
    resources :answers do
      member do
        get :upvote
        get :downvote
      end
    end
    member do
      get :upvote
      get :downvote
    end
  end

  get "users/show"
  get 'about' => 'pages#about'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  acts_as_votable

  belongs_to :user
  belongs_to :question

  validates :body, :presence => true, length: { minimum: 15 }
  validates :question_id, :presence => true
  validates :user_id, :presence => true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # CanCan
  load_and_authorize_resource except: [:create]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = current_user.answers.build
  end

  # GET /answers/1/edit
  def edit
    @question = Question.find(params[:question_id])
    @answer = current_user.answers.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @question = Question.find(params[:question_id])
    @answer = current_user.answers.build(answer_params)
    @answer.question_id = @question.id

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to question_path(@answer.question), notice: 'You edited your answer Successfully.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  # Upvote Question
  def upvote
    @answer = Answer.find(params[:id])
    @answer.upvote_from current_user
    increment_votes_count
    @answer.user.add_points(10)
    redirect_to :back
  end

  # Downvote Question
  def downvote
    @answer = Answer.find(params[:id])
    @answer.downvote_from current_user
    decrement_votes_count
    @answer.user.substract_points(2)
    redirect_to :back
  end

  def decrement_votes_count
    @answer.decrement!(:votes_count)
    @answer.save
  end

  def increment_votes_count
    @answer.increment!(:votes_count)
    @answer.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="question answers">
  <table>
    <tbody><tr>
      <td class="votecell">
        <div class="vote">

          <!--le Upvote-->
          <%= link_to upvote_question_answer_path(@question, answer), class: "question_vote_up" do %>
            <span class="glyphicon glyphicon-chevron-up"></span>
          <% end %>

          <!--le Votes Size-->
              <span class="question_vote_count">
                <%= answer.votes_count %>
              </span>

          <!--le Downvote-->
          <%= link_to downvote_question_answer_path(@question, answer), class: "question_vote_down" do %>
            <span class="glyphicon glyphicon-chevron-down"></span>
          <% end %>

        </div>
      </td>

      <td class="postcell">
        <div>
          <div class="post-text">
            <%= sanitize(answer.body) %>
          </div>

          <table class="fw">
            <tbody>
            <tr>

              <td class="vt answers_options">
                <div class="post-menu">
                  <a href="#" title="#" class="short-link">share</a>
                  <span class="lsep">|</span>
                  <% if can? :update, @answer %>
                    <%= link_to "edit", edit_question_answer_path(@question, answer) %>
                    <span class="lsep">|</span>
                  <% end %>
                  <% if can? :destroy, @answer %>
                    <%= link_to "delete", question_answer_path(@question, answer),
                                method: :delete, data: { confirm: 'Are you sure?' } %>
                    <span class="lsep">|</span>
                  <% end %>
                  <a href="#" class="flag-post-link" title="#">flag</a>
                </div>
              </td>

              <td class="post-signature owner">

                <div class="user-info ">
                  <div class="user-action-time">
                    answered <span title="#" class="relativetime"><%= time_ago_in_words answer.created_at %> ago</span>
                  </div>

                  <div class="user-avatar32">
                    <%= link_to @question.user do %>
                      <div>
                        <%= image_tag @question.user.avatar.url(:avatar) %>
                      </div>
                    <% end %>
                  </div>

                  <div class="user-details">
                    <%= link_to answer.user.user_name, answer.user %>
                    <br>
                    <span class="reputation-score" title="reputation score " dir="ltr"><%= answer.user.points %></span>
                  </div>

                </div>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
      </td>
    </tr>
    </tbody>
  </table>
  <br>
</div>
<br>

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_area :body, class: "redactor redactor-box" %>
  </div>
  <div class="actions">
    <%= f.submit "Post your Answer", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<%= form_for [@question, @answer] do |f| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-title">
        <h1>Edit your Answer</h1>
      </div>
    </div>

    <div class="panel-body">

      <div class="form-group">
        <%= f.text_area :body, class: "redactor redactor-box" %>
      </div>

    </div>


    <div class="panel-footer">
      <div class="actions">
        <button type="submit" class="ui-button button1">
          <span class="button-left">
            <span class="button-right"> Edit your Answer</span>
          </span>
        </button>

      <a href="javascript:history.back()">
        <button class="ui-button button1">
            <span class="button-left">
              <span class="button-right"> Back </span>
            </span>
        </button>
      </a>

      </div>
    </div>
  </div>
<% end %>

app/views/answers/index.html.erb
<%= render @answers %>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>