config/routes.rb
Hearthstoniav2::Application.routes.draw do


  mount RedactorRails::Engine => '/redactor_rails'
  resources :tags

  root 'questions#index'

  devise_for :users

  get 'users/:id' => 'users#show', as: :user

  resources :questions do
    resources :answers do
      member do
        get :upvote
        get :downvote
      end
    end
    member do
      get :upvote
      get :downvote
    end
  end

  get "users/show"
  get 'about' => 'pages#about'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => [:slugged, :finders, :history]

  belongs_to :question
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # CanCan
  load_and_authorize_resource except: [:create]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id]) 
      # param that was sent is called :id in case of update it sends id of tag, not name, so find_by_name will return false and it wil try to find by id
      # || this means OR  find this OR that, can't think of any other solution for the moment
      # all this find_by_name things are done in routes and it will overide the method find, so it won't look for the record by id,
      # it will look by whatever else param you'll set
      # and writing in form  form_for @tag  in html will return  the url /tags/tag_name/edit  and not tags/3/edit.
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :category, :card_type, :card_class,
                                  :card_cost, :card_attack, :card_health)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">
          <h1>Create a Tag</h1>
        </div>
      </div>

      <div class="panel-body">
        <%= form_for(@tag) do |f| %>
          <% if @tag.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

              <ul>
                <% @tag.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :category %><br>
            <%= f.text_field :category, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :card_type %><br>
            <%= f.text_field :card_type, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :card_class %><br>
            <%= f.text_field :card_class, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :card_cost %><br>
            <%= f.text_field :card_cost, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :card_attack %><br>
            <%= f.text_field :card_attack, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :card_health %><br>
            <%= f.text_field :card_health, class: "form-control" %>
          </div>

      </div>

          <div class="panel-footer">
            <div class="form-group">
              <%= f.submit "Create Tag", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
        </div>
  </div>

  <div class="col-md-3">
    <div class="panel panel-default">
      whats up
    </div>
  </div>
</div>

app/views/tags/_tag.html.erb
<%= tag.name %>
<%= link_to 'Show', tag %>
<% if can? :update, tag %>
  <%= link_to 'Edit', edit_tag_path(tag) %>
<% end %>
<% if can? :destroy, tag  %>
  <%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<br>

app/views/tags/edit.html.erb
<%= render 'form' %>

app/views/tags/index.html.erb
<div class="listing_tags">
  <h1>Listing tags</h1>
</div>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>
      <span class="tag-tooltip"
            data-original-title="There are three main types of cards: spell cards, equipment cards and minion cards">
        Type
      </span>
    </th>
    <th>
      <span class="tag-tooltip"
            data-original-title="Class is the primary determinant of a hero's powers and abilities">Class</span>
    </th>
    <th>
      <span class="tag-tooltip"
            data-original-title="Each card features a mana cost in the top-left corner, which indicates the amount of mana that must be expended to play that card, ranging from 0 to 10 mana. ">
        Cost
      </span>
    </th>
    <th>
      <span class="tag-tooltip"
            data-original-title="Minion cards feature an Attack value in the bottom-left corner">
        Attack
      </span>
    </th>
    <th>
      <span class="tag-tooltip"
            data-original-title="Minion cards feature an Health value in the bottom-right corner">
        Health
      </span>
    </th>
  </tr>
            </thead>
  <tbody>

  <% @tags.each do |tag| %>
    <tr>
      <td>
        <%= link_to tag.name, tag, class: "tag-tooltip",
                    'data-placement' => 'right',
                    :rel => "tooltip" %>

      </td>
      <td><%= tag.card_type %></td>
      <td><%= tag.card_class %></td>
      <td><%= tag.card_cost %> <span class="icon-mana"></span></td>
      <td><%= tag.card_attack %> <span class="icon-attack"></span></td>
      <td><%= tag.card_health %> <span class="icon-health"></span></td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/tags/new.html.erb
<%= render 'form' %>

app/views/tags/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @tag.category %>
</p>

<p>
  <strong>Type:</strong>
  <%= @tag.card_type %>
</p>

<p>
  <strong>Class:</strong>
  <%= @tag.card_class %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @tag.card_cost %>
</p>

<p>
  <strong>Attack:</strong>
  <%= @tag.card_attack %>
</p>

<p>
  <strong>Health:</strong>
  <%= @tag.card_health %>
</p>

<% if can? :update, @tag %>
<%= link_to 'Edit', edit_tag_path(@tag) %>
<% end %>