config/routes.rb
Hearthstoniav2::Application.routes.draw do


  mount RedactorRails::Engine => '/redactor_rails'
  resources :tags

  root 'questions#index'

  devise_for :users

  get 'users/:id' => 'users#show', as: :user

  resources :questions do
    resources :answers do
      member do
        get :upvote
        get :downvote
      end
    end
    member do
      get :upvote
      get :downvote
    end
  end

  get "users/show"
  get 'about' => 'pages#about'
end

app/views/layouts/_footer.html.erb
<div class="body-bot"></div>

<!--le Footer-->
<div class="site-footer">

  <ul class="site-footer-links right">
    <li><%= link_to "Tags", tags_path %></li>
    <li><%= link_to "Help", "#" %></li>
    <li><%= link_to "About", "#" %></li>
    <li>
      <a href="#" class="tag-tooltip"
              data-original-title="Coming soon" data-placement="left">Blog
      </a>
    </li>
  </ul>

  <%= link_to root_path do %>
    <span class="mega-octicon octicon-mark-github tag-tooltip" data-original-title="You rock and you know it !" data-placement="top">
    </span>
  <% end %>

  <ul class="site-footer-links">
    <li>© <%= Time.now.year %> Hearthstonia</li>
    <li><%= link_to "Facebook", "https://www.facebook.com/hearthstonia", :target => '_blank' %></li>
    <li><%= link_to "Twitter", "https://twitter.com/Hearthstonia", :target => '_blank' %></li>
    <li><a href="mailto:info@hearthstonia.com">Contact</a></li>
  </ul>
</div>

<br>

<!-- Debug Console -->
<%#= debug(params) if Rails.env.development? %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Hearthstonia", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Ask a Question", new_question_path %></li>
          <% if can? :create, @tags %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Tags<b class="caret"></b>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Tags", tags_path %></li>
                <li><%= link_to "Create Tag", new_tag_path %></li>

              </ul>
            </li>
          <% else %>
            <li><%= link_to "Tags", tags_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.first_name %> <span class="badge"><%= current_user.points %></span><b class="caret"></b>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "My Profile", current_user %></li>
              <li><%= link_to "Account Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hearthstonia</title>
  <%= favicon_link_tag '/favicon.ico'%>
  <%= favicon_link_tag '/favicon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">

    <!-- Devise Flash Messages -->
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, class: "alert alert-info") do%>
        <%=msg%>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%end%>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>

  </div>


</body>
</html>